<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Por favor, insira um destino para comear a pesquisar</name>
   <tag></tag>
   <elementGuidId>112d150f-bbcd-491c-bcee-e233d2e8defd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='indexsearch']/div[2]/div/form/div/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.feaba1002a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Por favor, insira um destino para começar a pesquisar.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dfb1a309-525a-4971-aa4d-07a8a5d1a0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feaba1002a</value>
      <webElementGuid>24dcbd7a-4e8f-454d-af96-128f21a0d62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Por favor, insira um destino para começar a pesquisar.</value>
      <webElementGuid>5324a5e1-e9c6-47a9-9aac-edd354e08ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;indexsearch&quot;)/div[@class=&quot;hero-banner-searchbox&quot;]/div[1]/form[1]/div[@class=&quot;ffb9c3d6a3 c9a7790c31 e691439f9a&quot;]/div[@class=&quot;e22b782521&quot;]/div[@class=&quot;b7ab62d599&quot;]/div[@class=&quot;a0f1aad3f3&quot;]/div[@class=&quot;feaba1002a&quot;]</value>
      <webElementGuid>ce02c03b-6208-4bb6-b8ec-88d1bf5badea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='indexsearch']/div[2]/div/form/div/div/div/div[2]/div</value>
      <webElementGuid>46b2f22c-3220-451f-8c88-edd8b3b91cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encontre sua próxima estadia'])[1]/following::div[14]</value>
      <webElementGuid>e27dfaf5-c584-4f63-b9c9-7418a5d4ca90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mais'])[1]/following::div[20]</value>
      <webElementGuid>c3660b57-e2a6-4ad1-b697-5040ccde91b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data de check-in'])[1]/preceding::div[1]</value>
      <webElementGuid>6c029631-8541-4639-9609-14ece2fec020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='—'])[1]/preceding::div[1]</value>
      <webElementGuid>60e6d27a-0018-429c-aedb-a3fe0569f58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Por favor, insira um destino para começar a pesquisar.']/parent::*</value>
      <webElementGuid>b440484c-5c49-473c-9c61-7756f0c831d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div</value>
      <webElementGuid>0a6f5bb0-9442-4901-b29f-2cdf15a4dc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Por favor, insira um destino para começar a pesquisar.' or . = 'Por favor, insira um destino para começar a pesquisar.')]</value>
      <webElementGuid>988205bf-1a6a-45b1-b0ff-5f8f93d0aeb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
