<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_2 adultos  0 criana  1 quarto</name>
   <tag></tag>
   <elementGuidId>48b4bb79-7862-4cc4-8e40-9a7c1c697eee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.a83ed08757.ebbedaf8ac.ada2387af8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;occupancy-config&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66ca7f8d-574b-44b1-b651-77a15be32c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>occupancy-config</value>
      <webElementGuid>79afb587-32de-4ca6-8d69-f04e1b02ada1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>:rf:</value>
      <webElementGuid>07feba50-e5b7-413d-9176-3872c247c29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ff0d44a5-52f7-45d0-b212-10c0403d0bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf091d69-fb4a-49a1-a2c6-6f01e799661d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a83ed08757 ebbedaf8ac ada2387af8</value>
      <webElementGuid>8a5903a8-bddc-412e-bce4-380c73a555b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2 adultos · 0 criança · 1 quarto</value>
      <webElementGuid>3a75f7b7-3b06-4d31-9b00-cb9431def4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;indexsearch&quot;)/div[@class=&quot;hero-banner-searchbox&quot;]/div[1]/form[1]/div[@class=&quot;ffb9c3d6a3 c9a7790c31 e691439f9a&quot;]/div[@class=&quot;e22b782521&quot;]/div[@class=&quot;d777d2b248&quot;]/button[@class=&quot;a83ed08757 ebbedaf8ac ada2387af8&quot;]</value>
      <webElementGuid>255b6c5f-18d6-46fe-b909-7cc45924496e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>6f7318bb-df17-4df3-af22-484b6b5329fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='indexsearch']/div[2]/div/form/div/div[3]/div/button</value>
      <webElementGuid>447d5548-84e9-4b65-be84-4254790a9d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sáb., 1º de jun.'])[1]/following::button[1]</value>
      <webElementGuid>faf23154-c465-4f61-a08d-7dd1d988e8bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='—'])[1]/following::button[2]</value>
      <webElementGuid>0983e1fa-9dc1-4b88-bd8b-5593c682af3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesquisar'])[1]/preceding::button[1]</value>
      <webElementGuid>fbeb9815-c07b-40a2-82cc-853102db458f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estou buscando casas e apartamentos inteiros'])[1]/preceding::button[2]</value>
      <webElementGuid>30baec67-f443-46ef-bbc2-eb228d50cc86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>bf12a9b8-de2a-4577-a21a-4902224aee3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '2 adultos · 0 criança · 1 quarto' or . = '2 adultos · 0 criança · 1 quarto')]</value>
      <webElementGuid>085c3c96-d6ab-4c36-a23c-afab653503e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
