<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pular para o contedo principal_f9966e6860</name>
   <tag></tag>
   <elementGuidId>711f1e4c-2b31-45f7-882c-760360421abb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='b2indexPage']/div[2]/div/div/header/nav/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.f9966e6860</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>nav >> internal:has-text=&quot;BRLAnuncie sua propriedadeCadastre-seLogin&quot;i >> div >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f994ec75-dfaf-47d1-809f-e1470facf482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f9966e6860</value>
      <webElementGuid>01989c5e-2de7-4b9b-a197-f39a37b5e0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2indexPage&quot;)/div[2]/div[1]/div[@class=&quot;web-shell-header-mfe ab4f62cc7e a1902a1d4e&quot;]/header[@class=&quot;b4ea8459d6&quot;]/nav[@class=&quot;c20fd9b542&quot;]/div[@class=&quot;f9966e6860&quot;]</value>
      <webElementGuid>8096d4ae-ca5d-4612-a4cb-e6c9e1a40aa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='b2indexPage']/div[2]/div/div/header/nav/div</value>
      <webElementGuid>d395c227-9c90-4b2e-9d2d-4fe6ef1f81e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pular para o conteúdo principal'])[1]/following::div[4]</value>
      <webElementGuid>ab469e04-26af-4ad8-9bcb-4d8feae15c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BRL'])[1]/preceding::div[2]</value>
      <webElementGuid>6de343bc-65c2-433b-a4ea-9dc5aa43e924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anuncie sua propriedade'])[1]/preceding::div[3]</value>
      <webElementGuid>000a60e3-c359-45ae-8bc4-95cc2d78c553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div</value>
      <webElementGuid>616f6757-19e1-4590-accc-dfdc293051d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
