<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pesquisar</name>
   <tag></tag>
   <elementGuidId>3f7a9a3d-9f79-4dad-8636-2d23287eade8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='indexsearch']/div[2]/div/form/div/div[4]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.a83ed08757.c21c56c305.a4c1805887.f671049264.d2529514af.c082d89982.cceeb8986b > span.e4adce92df</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Pesquisar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cd663264-b808-4921-9be8-339bf2f28804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e4adce92df</value>
      <webElementGuid>c862b706-e163-41d8-a7eb-09fab45cde57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesquisar</value>
      <webElementGuid>656f8937-0382-41f0-b486-fbd0bd4bf9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;indexsearch&quot;)/div[@class=&quot;hero-banner-searchbox&quot;]/div[1]/form[1]/div[@class=&quot;ffb9c3d6a3 c9a7790c31 e691439f9a&quot;]/div[@class=&quot;e22b782521 d12ff5f5bf&quot;]/button[@class=&quot;a83ed08757 c21c56c305 a4c1805887 f671049264 d2529514af c082d89982 cceeb8986b&quot;]/span[@class=&quot;e4adce92df&quot;]</value>
      <webElementGuid>e9e741f9-2180-449f-ad5c-ba5192f55343</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='indexsearch']/div[2]/div/form/div/div[4]/button/span</value>
      <webElementGuid>e0caf913-ab47-4e52-9560-dd7a56f690e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sáb., 1º de jun.'])[1]/following::span[4]</value>
      <webElementGuid>31accd54-fd4d-4ac1-82bf-c287ab66a51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='—'])[1]/following::span[5]</value>
      <webElementGuid>5aff5cf4-3c75-48d6-ad92-c80c28045b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estou buscando casas e apartamentos inteiros'])[1]/preceding::span[4]</value>
      <webElementGuid>e9dfbe99-5d86-436d-9ef1-2eb004a84dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estou buscando voos'])[1]/preceding::span[8]</value>
      <webElementGuid>a8bf0a88-6df0-4fd7-a295-7bc55353d7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pesquisar']/parent::*</value>
      <webElementGuid>3797235c-941b-4528-9d01-f34823fd79b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button/span</value>
      <webElementGuid>c874666f-3eb9-4e28-91e7-5efb687b4019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pesquisar' or . = 'Pesquisar')]</value>
      <webElementGuid>cb0d7923-29b7-4641-9e17-b17c537680a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
