<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1</name>
   <tag></tag>
   <elementGuidId>59286934-b144-4ad0-8641-1cef60184b2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='calendar-searchboxdatepicker']/div/div/div/div[2]/table/tbody/tr/td[7]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;1 junho 2024&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd577c91-f721-4375-8883-7064baa43aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5734e30c-0f9c-42df-8ebc-96f73f1082be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cf06f772fa ef091eb985</value>
      <webElementGuid>db9dca7c-556a-4a02-bd17-8797b3c957ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>2024-06-01</value>
      <webElementGuid>90a26808-d0c5-4f51-aa23-44dd6969fd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ec8a2e47-9887-402b-83ce-f926b63136cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f6b2af25-d882-41d0-9d45-55d9d7dece53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>1 junho 2024</value>
      <webElementGuid>1b93496e-8e29-4616-b972-a5ce4f0e01cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>896072c4-f3f5-4fe4-ba53-424dd40c0d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendar-searchboxdatepicker&quot;)/div[@class=&quot;c3b22e6fe5&quot;]/div[@class=&quot;a10b0e2d13 c807ff2d48&quot;]/div[@class=&quot;d4babb55ef&quot;]/div[@class=&quot;d358556c65&quot;]/table[@class=&quot;eb03f3f27f&quot;]/tbody[1]/tr[1]/td[@class=&quot;b80d5adb18&quot;]/span[@class=&quot;cf06f772fa ef091eb985&quot;]</value>
      <webElementGuid>2e6c5192-f030-43e9-9c3b-3282cd54ed0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calendar-searchboxdatepicker']/div/div/div/div[2]/table/tbody/tr/td[7]/span</value>
      <webElementGuid>096b01b2-0d03-4d0c-af33-0cd5f04e3bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa.'])[2]/following::span[1]</value>
      <webElementGuid>01c04beb-c7e1-4a38-9cf2-db81f2dac300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do.'])[2]/following::span[1]</value>
      <webElementGuid>ec966d0c-76d5-499c-9f59-6920de0d495d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datas exatas'])[1]/preceding::span[60]</value>
      <webElementGuid>faf7b59d-212e-4ae4-8a72-6cc42e084840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesquisar'])[1]/preceding::span[85]</value>
      <webElementGuid>acf64290-9288-4ffc-b604-328e7e686503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[7]/span</value>
      <webElementGuid>2c19301d-3831-43b3-9852-677f28e61812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1' or . = '1')]</value>
      <webElementGuid>b1deca99-e9cb-409d-8e72-2079014416f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
